import { useState, useEffect } from "react";

// Import images
import img1 from "../assets/images/banner-Privacy-Policy.webp";
import img2 from "../assets/images/home-hero-2.webp";
import img3 from "../assets/images/home-hero-3.webp";
import Navbar from "../Component/navbar"
import Location from "../Component/ContactUScontainer/Location";
import Introduction from "../Component/aboutuspagecontainer/Introduction";
import EmailContact from "../Component/Homecontainer/EmailContact";
import AboutUS from "./Homecontainer/aboutus";
import BritishTravelAwards from "./Homecontainer/britishTravelAward";
import { FaBox, FaPlane } from "react-icons/fa";
import Container from "./OurMisssionContainer/container";
import WhastappChat from "./Homecontainer/whatsapp";
import Objectives from "./OurMisssionContainer/objective";


export default function ContactUS() {
  const images = [img1, img2, img3];
  const [currentIndex, setCurrentIndex] = useState(0);
  
   const [selected, setSelected] = useState("package");

  // useEffect(() => {
  //   const interval = setInterval(() => {
  //     setCurrentIndex((prevIndex) => (prevIndex + 1) % images.length);
  //   }, 3000);

  //   return () => clearInterval(interval);
  // }, [images.length]);

  return (
    <div>
        <Navbar/>
        <div className="relative h-[130px]"></div>
    <div className="w-full h-[300px] sm:h-[400px] lg:h-[500px] relative">
  {/* Image - this part is fine */}
  <img
    src={images[currentIndex]}
    alt="Hero"
    className="w-full h-full object-cover transition-opacity duration-1000"
  />

  {/* Dots - could be smaller on mobile */}
  <div className="absolute top-1/2 right-2 sm:right-4 -translate-y-1/2 flex flex-col space-y-2">
    {images.map((_, index) => (
      <button
        key={index}
        onClick={() => setCurrentIndex(index)}
        className={`w-2 h-2 sm:w-3 sm:h-3 rounded-full ${
          index === currentIndex ? "bg-white" : "bg-gray-400"
        } hover:bg-white transition-colors duration-300`}
      />
    ))}
  </div>

  {/* Responsive text */}
  <div className="absolute bottom-[40%] left-1/2 transform -translate-x-1/2 flex items-center justify-center">
    <div className="text-white font-semibold text-2xl sm:text-4xl lg:text-6xl text-center px-4">
      
    </div>
  </div>
</div>
    
   <div className="max-w-4xl mx-auto px-6 py-8">
      <main>
        <article className="space-y-6">
          <div>
            <h1 className="text-4xl font-bold mb-2">Privacy Policy</h1>
            <p className="text-gray-600 mb-4">
              <strong>Last updated:</strong> August 26, 2025
            </p>
          </div>

         <p className="text-gray-700 leading-relaxed">This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
<p className="text-gray-700 leading-relaxed">We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the <a href="https://www.termsfeed.com/privacy-policy-generator/" target="_blank">Privacy Policy Generator</a>.</p>


        <h2 className="text-3xl font-bold mb-2">Interpretation and Definitions</h2><br></br>
<h2 className="text-2xl font-semibold">Interpretation</h2>
<p className="text-gray-700 leading-relaxed">The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>



          <section className="space-y-4">
            <h2 className="text-2xl font-semibold">Definitions</h2>
            <ul className="space-y-2 pl-6">
              <li><strong>Company</strong>: <p className="text-gray-700 leading-relaxed"> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to Godwit Holidays.</p></li>
              <li><strong>Personal Data</strong>:<p className="text-gray-700 leading-relaxed"> Any information that identifies you or can be used to identify you.</p></li>
              <li><strong>Service</strong>:<p className="text-gray-700 leading-relaxed">The Godwit Holidays website and related services.</p></li>
              <li><strong>Usage Data</strong>: <p className="text-gray-700 leading-relaxed">refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p></li>
             
             <li><strong>Device</strong>:<p className="text-gray-700 leading-relaxed"> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</p></li>
              <li><strong>You</strong>:<p className="text-gray-700 leading-relaxed"> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable. </p></li>
            
            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold">Information We Collect</h2>
            
            <div className="space-y-3">
              <h3 className="text-xl font-medium">Personal Data you provide</h3>
              <p className="text-gray-700 leading-relaxed">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>


              <ul className="space-y-1 pl-6">
                <li className="text-gray-700 leading-relaxed">Name, email, phone number</li>
                <li className="text-gray-700 leading-relaxed">Booking details (dates, destinations, preferences, special requirements)</li>
                <li className="text-gray-700 leading-relaxed">Billing details and passport info (when required to process bookings)</li>
              </ul>
            </div>

            <div className="space-y-3">
              <h3 className="text-xl font-medium">Usage Data (collected automatically)</h3>
              <p>Usage Data is collected automatically when using the Service.</p>
              <p className="text-gray-700 leading-relaxed">
                We may collect IP address, browser type/version, device identifiers, pages visited, time spent,
                and similar diagnostics. On mobile, we may collect device model, OS, and app/browser details.
              </p>

              <p className="text-gray-700 leading-relaxed"> Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
<p className="text-gray-700 leading-relaxed"> When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
<p className="text-gray-700 leading-relaxed"> We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>

            </div>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold">How We Use Your Information</h2>
            {/* <ul className="space-y-1 pl-6">
              <li>Provide, operate, and improve the Service</li>
              <li>Process bookings and deliver travel services</li>
              <li>Communicate about itineraries, updates, offers (you can opt out anytime)</li>
              <li>Detect, prevent, and address technical or security issues</li>
              <li>Comply with legal obligations</li>
            </ul>

            <h3>Use of Your Personal Data</h3> */}
<p>The Company may use Personal Data for the following purposes:</p><br></br>
<ul>
<li>
<p><strong>To provide and maintain our Service</strong><p className="text-gray-700 leading-relaxed"> , including to monitor the usage of our Service.</p></p>
</li><br></br>
<li>
<p><strong>To manage Your Account:</strong> <p className="text-gray-700 leading-relaxed"> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</p></p>
</li><br></br>
<li>
<p><strong>For the performance of a contract:</strong><p className="text-gray-700 leading-relaxed">  the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</p></p>
</li><br></br>
<li>
<p><strong>To contact You:</strong><p className="text-gray-700 leading-relaxed">  To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</p></p>
</li><br></br>
<li>
<p><strong>To provide You</strong><p className="text-gray-700 leading-relaxed">  with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</p></p>
</li><br></br>
<li>
<p><strong>To manage Your requests:</strong><p className="text-gray-700 leading-relaxed">  To attend and manage Your requests to Us.</p></p>
</li><br></br>
<li>
<p><strong>For business transfers:</strong><p className="text-gray-700 leading-relaxed">  We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</p></p>
</li><br></br>
<li>
<p><strong>For other purposes</strong><p className="text-gray-700 leading-relaxed"> : We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</p></p>
</li><br></br>
</ul>

          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold">Sharing Your Information</h2>
            <p className="text-gray-700 leading-relaxed mb-3">We do not sell your Personal Data. We may share it with Your personal information in the following situations:</p>
            <ul className="space-y-5 pl-6">
          <li><strong>With Service Providers:</strong><p className="text-gray-700 leading-relaxed"> We may share Your personal information with Service Providers to monitor and analyze the use of our Service,  to contact You.</p></li>
<li><strong>For business transfers:</strong><p className="text-gray-700 leading-relaxed"> We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</p></li>
<li><strong>With Affiliates:</strong><p className="text-gray-700 leading-relaxed"> We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.</p></li>
<li><strong>With business partners:</strong> <p className="text-gray-700 leading-relaxed"> We may share Your information with Our business partners to offer You certain products, services or promotions.</p></li>
<li><strong>With other users:</strong> <p className="text-gray-700 leading-relaxed"> when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.</p></li>
<li><strong>With Your consent :</strong><p className="text-gray-700 leading-relaxed"> We may disclose Your personal information for any other purpose with Your consent.</p></li>

            </ul>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold">Data Retention</h2>
           

            <p className="text-gray-700 leading-relaxed">The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
<p className="text-gray-700 leading-relaxed"> The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.</p>

          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold">International Transfers</h2>
            

            <p className="text-gray-700 leading-relaxed">Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.</p>
<p className="text-gray-700 leading-relaxed">Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>
<p className="text-gray-700 leading-relaxed" >The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</p>

          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold">Your Rights</h2>
            <p className="text-gray-700 leading-relaxed">You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.</p>
<p className="text-gray-700 leading-relaxed">Our Service may give You the ability to delete certain information about You from within the Service.</p>
< p className="text-gray-700 leading-relaxed">You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.</p>
<p className="text-gray-700 leading-relaxed">Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.</p>

          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold">Security</h2>
            <p className="text-gray-700 leading-relaxed">The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data.</p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold">Children's Privacy</h2>
            
            <p className="text-gray-700 leading-relaxed">Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.</p>
<p className="text-gray-700 leading-relaxed">If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.</p>

          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold">Links to Other Sites</h2>
            <p className="text-gray-700 leading-relaxed">
             Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
<p className="text-gray-700 leading-relaxed">We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>

          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold">Changes to This Policy</h2>
            <p className="text-gray-700 leading-relaxed">
             We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
<p className="text-gray-700 leading-relaxed">We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the &quot;Last updated&quot; date at the top of this Privacy Policy.</p>
<p className="text-gray-700 leading-relaxed">You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>

          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold">Contact Us</h2>
            <address className="not-italic text-gray-700 leading-relaxed space-y-1">
              <div><strong>Godwit Holidays</strong></div>
              <div>Email: <a href="mailto:info@godwitholidays.com" className="text-blue-600 hover:underline">info@godwitholidays.com</a></div>
              <div>Phone: <a href="tel:+1123456789" className="text-blue-600 hover:underline">+1 123-456-789</a></div>
              <div>Website: <a href="http://www.godwitholidays.com" target="_blank" rel="noopener" className="text-blue-600 hover:underline">www.godwitholidays.com</a></div>
            </address>
          </section>

          <p className="text-gray-700 leading-relaxed border-t pt-4">
            For details on cookies and similar technologies, see our{' '}
            <a href="/cookie-policy" className="text-blue-600 hover:underline">Cookie Policy</a>.
          </p>
        </article>
      </main>
    </div>
   
   <EmailContact />
    <AboutUS />
    <BritishTravelAwards />
    <WhastappChat/>
   
     
    
    </div>
  );
}
